---
- name: Install Docker
  hosts: aws_ec2
  become: yes
  gather_facts: False
  tasks:
    - name: Install Python3 and docker
      vars: 
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present

- name: Install docker-compose
  hosts:
  become: yes
  tasks:
    - name: Download docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Install docker python module
      pip:
        name: 
          - docker
          - docker-compose


- name: Start Docker Daemon
  hosts:
  beocme: true
  tasks:
    - name: Start docker daemon
      systemd:
        name: docker
        state: started
    
    
- name: Create new Linux User
  hosts:
  become: true
  tasks:
    - name: Create Linux User
      user:
        name: fatima
        groups: "{{user_groups}}"


- name: Test docker run
  hosts:
  tasks:
    - name: Pull redis
      docker_image:
        - name: redis
          source: pull


- name: Start docker container
  hosts:
  become: yes
  become_user: fatima
  vars_files:
    - project-vars
  tasks:
    - name: copy docker compose file
      copy:
        src: /root/ansible/docker-compose-full.yaml
        dest: /home/fatima/docker-compose.yaml
    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: fatima0
        password: "{{password}}"
    - name: Run docker-compose
      docker_compose:
        project_src: /home/fatima
        #state: present docker-compose up, present is the default state, so we don't specify