---
plugin: aws_ec2
regions:
  - ap-south-1
aws_access_key: "AKIA5PCN6HLATMRPA2YZ"
aws_secret_key: "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"
keyed_groups:
  - key: tags
    prefix: tag
  - key: instance_type
    prefix: instance_type

